### ISSUE TITLE
These Credentials do not match

### ISSUE THREAD

**Issue by anukwgl** [jotaelesalinas/laravel-simple-ldap-auth#1]
@jotaelesalinas so I have pre-installed laravel and when i change the ladp with different server, I followed same steps but couldn't Login.

**Comment by jotaelesalinas** [comment]
1) Can you log in with the testing server?
2) It is not normal for LDAP servers to use "uid", it is more common "cn". Have you checked?

Ask you LDAP admin for an example full DN needed to login and start working on that.

**Comment by anukwgl** [comment]
yes I can log in with testing server, I will check with LDAP admin and start working on it.
I have ip adress of LDAP: ldap://000.00.000.00
ldaprdn=***
base_dn=dc=***, dc=***
 Thank you

**Comment by anukwgl** [comment]
Can you help me, there is just a common cn, so what do i need to change instead of uid?

**Comment by jotaelesalinas** [comment]
Try changing every occurrence of `uid` with `cn` in `.env`. Also, look your server's logs.

**Comment by jotaelesalinas** [comment]
Are you sure that the IP address is 000.00.000.00? Doesn't look like anything to me...

**Comment by anukwgl** [comment]
I gave an example of my IP address, my address is different

**Comment by anukwgl** [comment]
Can i use samaccountname instead of uid?
 'ldap' => env('ADLDAP_USER_ATTRIBUTE', 'userprincipalname'), // cahnge to samacoountm=name
 'sync_attributes' => [
        'username' => 'uid', // samaccountname
        'name' => 'cn',
ADLDAP_USER_ATTRIBUTE=uid //samaccountname
ADLDAP_USER_FORMAT=uid=%s,dc=example,dc=com // samaccountname=%s

**Comment by jotaelesalinas** [comment]
Sure! Try that. Each LDAP server is different. I am aware that the public one used for testing is not a very standard setup.

**Comment by jotaelesalinas** [comment]
Hi @anukwgl , any news? Did you finally work it out?

**Comment by anukwgl** [comment]
It didn't work out, Thanks for the follow up am still working on it.

**Comment by jotaelesalinas** [comment]
Check if you have to use ldaps (like https).

**Comment by anukwgl** [comment]
The ldap server I wanted to use is an IP address

**Comment by jotaelesalinas** [comment]
Yes, but in the case that it is LDAP over SSL (ldaps://xx.xx.xx.xx), you have to change the configuration in `config/adldap.php`. Set `connections.default.connection_settings.use_ssl` to `true`. Try also with `use_tls`. It's just a possibility; the chances of the problem being this are very low.

**Comment by anukwgl** [comment]
I will give it a try thank you.

**Comment by anukwgl** [comment]
Will this code work for the Active Directory?
