### ISSUE TITLE
Help needed to configure LDAP

### ISSUE THREAD

**Issue by riyazpt** [jotaelesalinas/laravel-simple-ldap-auth#10]
Hi,
I tried  to connect LDAP native php  with following parameters 
    $dsn              ="india.local";
    $username    ="india\\abcd.efg";
    $password       ="xxxxx"
     $ds               = ldap_connect($dsn,389);
     $connection = ldap_bind($ds,username,$password);
    dd($connection );
which returns TRUE;

But I couldn't configure these settings in config/adldap.php and config/adldap_auth.php

Please help  to configure settings .

**Comment by jotaelesalinas** [comment]
Sorry but I cannot help you here. You will have to ask your LDAP administrator for the proper configuration values.

**Comment by riyazpt** [comment]
Dear sir,
I asked to server administrator.
He said internally all managed i donot require any Ip
My
Username will be : \\abc. India
Password :xxx
Dsn for connection :india.local
With core php ladap_connect () is succesfull
Pls help.
