### ISSUE TITLE
Trait HasLdapUser not work

### ISSUE THREAD

**Issue by jhosepharaujo** [jotaelesalinas/laravel-simple-ldap-auth#13]
I added the trait in the User model but it did not work correctly. The ldap attr returns null. Here is the template and the return of dd() method.

<pre>

namespace App;

use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasLdapUser;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
</pre>

My result

<pre>
User {#229 ▼
  #fillable: array:4 [▶]
  #hidden: array:2 [▶]
  #connection: "sqlite"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:8 [▶]
  #original: array:8 [▶]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  +ldap: null
</pre>

The +ldap is null.

How to solve this problem?

**Comment by jotaelesalinas** [comment]
The library `Adldap` was built to work with an admin LDAP account. If you don't have such admin account, follow the instructions and you will be able to authenticate users against an LDAP server.

**Comment by jotaelesalinas** [comment]
Don't use the `HasLdapUser` trait and follow the tutorial.
