### ISSUE TITLE
Cant Authenticate

### ISSUE THREAD

**Issue by mybigman** [jotaelesalinas/laravel-simple-ldap-auth#14]
Hi,

I am using the latest Laravel and Adldap2-Laravel and it keeps wanting to pass the admin username and password across and not the users details :/

Does this still work for the latest version?

Thanks.

**Comment by jotaelesalinas** [comment]
It should. Did you go through all the steps in the instructions?

**Comment by mybigman** [comment]
Sure did... In the end I had go a different approach, took a bit to solve :/

```php
$provider = \Adldap::getDefaultProvider();
$provider->auth()->bind($creds['username'], $creds['password']);
$provider->auth()->attempt($creds['username'], $creds['password'], true);
```

Thanks

**Comment by jotaelesalinas** [comment]
Ok, thanks. I added a comment with a reference to this issue.

**Comment by turaza** [comment]
@jotaelesalinas Hi, if it's possible can you help me? I do ldap authorization on laravel first time. Your code not work for me. I have Windows Active Directory. Laravel version 5.3.*.

**Comment by raghavendrasandeep** [comment]
Hi,

I am using the latest Laravel and Adldap2-Laravel and all installation went well but when I check to the login page showing

BadMethodCallException
Method App\Http\Controllers\Auth\LoginController::showLoginForm does not exist.

Any suggestions.

Thanks

**Comment by jotaelesalinas** [comment]
No idea. Have you run `php artisan ui vue --auth`?

**Comment by turaza** [comment]
You need run command --auth before installing adldap2.

вт, 14 янв. 2020 г., 16:57 raghavendrasandeep <notifications@github.com>:

**Comment by Zakirp4** [comment]
if(Adldap::auth()->attempt($userdn, $password, $bindAsUser = true))
It showing an error---------
UnexpectedValueException
The Response content must be a string or object implementing __toString(), "boolean" given.
http://localhost:8000/login

**Comment by Zakirp4** [comment]
at last solved.....................
LoginController.php
if(Adldap::auth()->attempt($username, $password, $bindAsUser = true))

ldap.php
'username' => env('xxxx@test.com')
