### ISSUE TITLE
How to set time expire for remember token

### ISSUE THREAD

**Issue by khoapercy** [jotaelesalinas/laravel-simple-ldap-auth#16]
Hi , My name is Percy , I was use laravel 5.4 with your source LDAP .  Everything is ok and good
So I have issue like that :
When I logged in on my LDAP , I can not logout when I close my browser . It only logout until I click logout button . 
So how I can set time expire for remember_token  (?)
Remember _token create a cookie with name is remember_web_(string hashed) with year is 2025 
So how can I change that time in 6 hours  v.v...  (?)
Please help me

**Comment by jotaelesalinas** [comment]
I think that the line:

    $this->guard()->login($user, true);

should read:

    $this->guard()->login($user, false);

Please, let me know if that works and I will add a comment mentioning this.

**Comment by khoapercy** [comment]
Thank you so much for your help 
It worked .

**Comment by jotaelesalinas** [comment]
You're welcome!
