### ISSUE TITLE
Authentication happens via Admin credentials always 

### ISSUE THREAD

**Issue by pbvignesh** [jotaelesalinas/laravel-simple-ldap-auth#18]
This issue is similar to issue number #14, no matter what configuration value I set it tries to bind via the administrator credentials, I noticed that you have already made a note of this and included a note in your post. But it feels more like a workaround than an actual fix? Should we come up with a proper solution and fix it in the original plugin itself ? I can provide more information on what is happening in the code if needed.

Thanks

**Comment by jotaelesalinas** [comment]
Sure! Is it an issue with Adldap2-Laravel or with these instructions? You can always create a pull request. But I am concerned with the fact that only some users experience this issue. We have to come up with a solution that works for everyone.
