### ISSUE TITLE
How to remove remember cookie when I close browser 

### ISSUE THREAD

**Issue by khoapercy** [jotaelesalinas/laravel-simple-ldap-auth#19]
Hi , 
I want delete cookie when I close browser 
I try to  set  $this->guard()->login($user, false);
Ok I can remove cookie and return login page when I closes the browser
But I dicsover one thing  , I can not login again if i'm new user (It meam my username have not in database yet before) else ok 
Please help me fix this issue , I can close brower . delete cookie and login nomally when I'm new user
Thank and best regards

**Comment by jotaelesalinas** [comment]
Not related to this specific LDAP implementation. Closing.
