### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by pittierfa** [jotaelesalinas/laravel-simple-ldap-auth#21]
(I know itsn't the right place but I didn't know where to ask... )
I've followed your tutorial but for me itsn't working, I would like to know if you could watch my code and tell me if you see something that look false.
If yes tell me where I could write you. And if you don't want / don't have time / etc just tell me and I'll delete this issue.

**Comment by jotaelesalinas** [comment]
Sorry, I really can't. Just try again and if it still doesn't work, let me know what error message you are receiving. Try to log as much as you can, to see where the error is generated.

**Comment by pittierfa** [comment]
I got no error and nothing in log, when I try to sign in i'm not connected and that's all

**Comment by evilfishcoco** [comment]
I have the same issue.

**Comment by jotaelesalinas** [comment]
Closing as I can't really help with specific implementations. Sorry.
