### ISSUE TITLE
Username with space

### ISSUE THREAD

**Issue by AndreaRunner** [jotaelesalinas/laravel-simple-ldap-auth#25]
Hi, how can i use a username with space ?

**Comment by jotaelesalinas** [comment]
You can try something while entering the username in the text box (not very user friendly, I know):

- Add `\` before the space
- Enclose the username in quotes `"`

Preferably, you should try in the code (I am going to use pseudocode):

- If username contains ' ', then username = username.replace(' ', '\\ ')
or
- If username contains ' ', then username = '"' . username . '"'

Please, let me know if it works and I will update the instructions!

**Comment by AndreaRunner** [comment]
Thanks.
i've no problem with this:
//$strLDAP_DN = $strUser;
$strLDAP_DN = $strDomain.'\\' . $strUser;

$ldapconn = ldap_connect($strADServer)
  or die("<h1>Could not connect to LDAP server</h1>");
	
ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3)
  or die("<h1>Could not set LDAP PROTOCOL VERSIONE to 3 </h1>");
  
ldap_set_option($ldapconn, LDAP_OPT_REFERRALS, 0)
  or die("<h1>Could disable LDAP referrals");
 
ldap_start_tls($ldapconn)
  or die("<h1>Could  not start secure TLS LDAP connection");	  

$ldapbind = @ldap_bind($ldapconn, $strLDAP_DN, $strPassword);

/*****************************************************************************************/
is possible to have this step by step guide for Laravel 5.7 and adldap 4.0 ?
/*****************************************************************************************/

**Comment by jotaelesalinas** [comment]
I googled the issue of spaces in usernames with LDAP and there seems to be no easy answer.

I am really sorry but I can't do another guide for the latest versions of Laravel and Adldap2/Adldap2-Laravel.
