### ISSUE TITLE
Method App\Http\Controllers\Auth\LoginController::showLoginForm does not exist.

### ISSUE THREAD

**Issue by jeremiahsherrill** [jotaelesalinas/laravel-simple-ldap-auth#26]
I keep getting this error, and there is no method.  Copied everything directly

**Comment by jotaelesalinas** [comment]
The method `showLoginForm()` is inside the trait `AuthenticatesUsers`, which is used by `LoginController`.

Bear in mind that you don't have to replace the contents of the file with the code of the tutorial, you have to _add_ it to the existing code.

**Comment by jeremiahsherrill** [comment]
thanks
