### ISSUE TITLE
Get groups

### ISSUE THREAD

**Issue by viandanteoscuro** [jotaelesalinas/laravel-simple-ldap-auth#3]
Hi to all,

I've followed this tutorial, and works great!
But... how can i access the user groups?
With the bind user model = true, doesn't work...

Thanks

**Comment by jotaelesalinas** [comment]
Hi @viandanteoscuro .

Try adding an entry to the array `sync_attributes` in file ` config/adldap_auth.php`.

You will have to create a new column in the `User` table of your database (create a new migration or modify existing one if you are starting from scratch).

If the LDAP entry with the groups is called `groups` (comma-separated?) and the new column in your database is called `roles`, you would add this entry to the array:

```php
    'roles' => 'groups',
```

I haven't tried this myself, but I really hope it helps!

**Comment by viandanteoscuro** [comment]
Nothing... does't work...
The LDAP entry is memberOF, and there are several of this...

Is there a metohd to dump all ldap record that adldap search for?

**Comment by jotaelesalinas** [comment]
Sorry, I have no idea how to solve that. Just out of curiosity, what do you get when you add `'roles' => 'memberOF'` to the array?

**Comment by jotaelesalinas** [comment]
Hi @viandanteoscuro , I have updated the manual with instructions to read and save extra attributes from the LDAP server. I hope it helps. Right now, if the attribute is an array in the server, it takes the first item; but I think that you can easily change it to read all of the values as a comma-separated string or any other way that fits your needs.
