### ISSUE TITLE
These credentials do not match our records

### ISSUE THREAD

**Issue by joaomiguelvieira** [jotaelesalinas/laravel-simple-ldap-auth#30]
Hi! I just followed the tutorial step-by-step, several times, and the outcome is allways the same: These credentials do not match our records. I am unable to authenticate... Also, no logs are produced

**Comment by jotaelesalinas** [comment]
Hi @joaomiguelvieira , try adding a `var_dump(compact(['username', 'password', 'user_format', 'userdn'])); exit;` before the `return false;` in `LoginController:: attemptLogin()`. See if all variables look ok.

**Comment by jotaelesalinas** [comment]
Thank you very much, @mmltonge !

**Comment by joaomiguelvieira** [comment]
Thanks all!

I will try that and I will report if it worked!

Kind regards,
Joao Vieira

On Jan 22, 2019, at 12:51 PM, José Luis Salinas <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much, @mmltonge<https://github.com/mmltonge> !

**Comment by jhosepharaujo** [comment]
Hi, i have the same problem. My credentials are ok. Any sugestion?

**Comment by mrjuri** [comment]
Hi @jotaelesalinas, thank you for your document.

Laravel 5.2.45
Adldap2-Laravel v3.0.5
PHP 5.6.40

I have same result: "These credentials do not match our records."

I sure credentials are correct, my code is a porting of actual project, so I rewrite all in Laravel.

The only difference with all your guide is "app/Http/Controllers/Auth/LoginController.php" file, in my Laravel version I have "app/Http/Controllers/Auth/AuthController.php".

I add into "app/Http/Controllers/Auth/AuthController.php":

`protected $username = 'username';`

and into "config/adldap.php":

`'auto_connect' => false,`

That's all, I don't have any other idea to solve this problem.

**Comment by javiertigre** [comment]
Y para conectarte y logearte con active directory que cambios se hacen??? a

**Comment by jotaelesalinas** [comment]
I am sorry, @javiertigre , I have never used it. You will have to ask your LDAP administrator.
