### ISSUE TITLE
Connection problem: Base table or view not found: 1146 Table 'roles' doesn't exist

### ISSUE THREAD

**Issue by pablolacerda** [jotaelesalinas/laravel-simple-ldap-auth#32]
Hi. 
First, Congrats for the project.
Sometimes an error appears when I try to log in. 
Error: **Base table or view not found: 1146 Table 'roles' doesn't exist (SQL: select * from `roles` where `name` = user limit 1)**
Class: **Illuminate/Database/Connection.php**
So, I go back to the screen, press F5 and try again. So it works correctly. This usually occurs when a new user is created in local database.

**my .env configuration**
LDAP_SCHEMA=ActiveDirectory
LDAP_HOSTS= '**myIP**'
LDAP_BASE_DN='**myBaseDN**'
ADLDAP_USER_ATTRIBUTE=samaccountname
LDAP_USER_FORMAT=samaccountname=%s,DC='**myBaseDN**',DC='**myBaseDN**'
LDAP_CONNECTION=default

**adldap.php**
'connections' => [
        'default' => [
            'auto_connect' => false,
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', '**myIP**')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'myBaseDN'),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', '**myUser**'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', '**myPsw**'),
                'follow_referrals' => true,
                'use_ssl' => false,
                'use_tls' => false,
            ],
        ],

i´m using :  
adldap2/adldap2-laravel": "3.0.5"
"laravel/framework": "5.5.*"

Do you have any ideas that can help me ?

Thank you.

**Comment by jotaelesalinas** [comment]
I don't think this issue is related to this repo, as there is no `roles` table anywhere.

Anyway, Look at the stack trace to find where the SQL call to the table `roles` is done and make sure that you really have a table `roles`.

**Comment by pablolacerda** [comment]
Ok, I finally figured it out. It was incomplete Voyager installation. I
removed the whole Voyager package and it now works

*composer remove tcg/voyager*

thanks
