### ISSUE TITLE
database connection 

### ISSUE THREAD

**Issue by nahuelmellusso** [jotaelesalinas/laravel-simple-ldap-auth#34]
Hi luis , i trying to connect with my database and make a login but always return false. 

this parametere should by my database ? 

LDAP_SCHEMA=databasename

or always

LDAP_SCHEMA=OpenLDAP ?

**Comment by jotaelesalinas** [comment]
`LDAP_SCHEMA` has to be one of these values: `OpenLDAP`, `FreeIPA` or `ActiveDirectory`.

Ask your LDAP administrator for the specific configuration values.

For the database configuration you use the default `DB_CONNECTION`, `DB_HOST`, `DB_PORT`, **`DB_DATABASE`**, `DB_USERNAME` and `DB_PASSWORD`.

**Comment by nahuelmellusso** [comment]
I see , thanks man !

**Comment by nahuelmellusso** [comment]
only one question , laravel continue using bycrypt to hash passwords ??  i can connect to database and retrive user but login fails ,  its not a new database so i must use password column that i have now

**Comment by nahuelmellusso** [comment]
Finally login its working , but i dont know  is redirecting to login view , and user is not logued , but atemplogin function return true , and auth()->check() return true inside atemp function.
