### ISSUE TITLE
LDAP Givenname

### ISSUE THREAD

**Issue by jeadriano** [jotaelesalinas/laravel-simple-ldap-auth#4]
How can i get the 'givenname' after successful Adlap::auth->attemp()?

**Comment by jeadriano** [comment]
i added **givenname** in **sync_attributes** in file **config/adldap_auth.php**
```
'sync_attributes' => [

        'username' => 'uid',
        'name' => 'cn',
        'givenname' => 'givenname'
    ],

```
my question is, how can i retrieve the givenname after successful Adldap::auth()->attempt().

**Comment by jotaelesalinas** [comment]
In theory, that's the way to do it. Didn't it work?

Have you added the column `givenname` to your database? You have to either add the column in `database/migrations/2014_10_12_000000_create_users_table.php` or, if you already run that migration, [create a new migration](https://laravel.com/docs/5.5/migrations):

```php
$table->string('givenname');
```

And then, in the `User` model (file `app/User.php`):

```php
protected $fillable = [
    'name', 'username', 'password', 'givenname',
];
```

Hope this helps!

**Comment by jeadriano** [comment]
yes i have givenname column in my table users, what im trying to do is to get the details "givenname" from active directory after a successful attemp. because i have to give value to "givenname" field in my table.

here is my code:
`protected function attemptLogin(Request $request) {
        $credentials = $request->only($this->username(), 'password');
        $username = $credentials[$this->username()];
        $password = $credentials['password'];
        
        if(Adldap::auth()->attempt($username, $password, $bindAsUser = true)) {
            // the user exists in the LDAP server, with the provided password
            $user = User::where($this->username(), $username)->first();
            if(!$user){
                // the user doesn't exist in the local database
                $user = new User();
                $user->givenname= $givenname; // get from AD user details after successful attemp
                $user->username = $username;
                $user->div_id = '1';
                $user->password = bcrypt('secret');
            }

            // by logging the user we create the session so there is no need to login again (in the configured time)
            $this->guard()->login($user, true);
            
            return true;
        }
        
        // the user doesn't exist in the LDAP server or the password is wrong
        return false;
    }`

thank you.

**Comment by jotaelesalinas** [comment]
Hi @jeadriano , I have updated the manual with instructions to read and save extra attributes from the LDAP server. I hope it helps. Right now, if the attribute is an array in the server, it takes the first item; but I think that you can easily change it to read all of the values as a comma-separated string or any other way that fits your needs.

**Comment by sbrem00** [comment]
I came across this problem and it turned out to be a case issue. 

If the method exists to get the value in the ldap User class you can use any case as methods are case insensitive. If the getter method does not exist in the ldap User class then it gets the value from an array (taken from the attributes of the user object as the attributes in the object may be protected). In this case the array key is case sensitive so needs to be exact. 

In my case I changed 'givenName' to 'givenname' in the sync_attributes in adldap_auth.php and it works. 

Check what the user attributes are that are returned by the search to see the exact names for your ldap server.

**Comment by jotaelesalinas** [comment]
Thanks for the information! I just created issue #9 as a reminder to fix it.
