### ISSUE TITLE
BindException due to Invalid DN syntax

### ISSUE THREAD

**Issue by sbrem00** [jotaelesalinas/laravel-simple-ldap-auth#6]
Hi, I'm new to LDAP auth and am having problems with binding and i am hoping you could help. 

I have followed the instructions provided and installed the laravel-simple-ldap-auth libraries. 
I am using the online LDAP test server for testing until i get it all working as needed. 

I keep getting the above bind exception and when i have looked at the stack trace it appears that  the connection is not already bound so it's trying to bind as administrator. I haven't specified an admin user and password as I just want to bind and authenticate as a user. I re-read the instructions and it does not mention having to bind as an administrator.

Here are the functions that are run after Adldap::auth()->attempt($userdn, $password, $bindAsUser = true)) is run:

__call function is run in vendor/adldap2/adldap2/src/Adldap.php

```
    public function __call($method, $parameters)
    {
        $provider = $this->getDefaultProvider();
 
        if (!$provider->getConnection()->isBound()) {
            // We'll make sure we have a bound connection before
            // allowing dynamic calls on the default provider.
            $provider->connect();
        }
 
        return call_user_func_array([$provider, $method], $parameters);
    }
```

in the above the $provider->getConnection()->isBound() returns false so the $provider->connect() function is run. 

vendor/adldap2/adldap2/src/Connections/Provider.php

```
    public function connect($username = null, $password = null)
    {
        // Get the default guard instance.
        $guard = $this->getGuard();
 
        if (is_null($username) && is_null($password)) {
            // If both the username and password are null, we'll connect to the server
            // using the configured administrator username and password.
            $guard->bindAsAdministrator();
        } else {
            // Bind to the server with the specified username and password otherwise.
            $guard->bind($username, $password);
        }
 
        return $this;
    }
```

As no passwords were passed through to the connect function both the $username and $password are null so the $guard->bindAsAdministrator(); function is run. 

the bindAsAdministrator() function then calls the bind() function with the admin credentials (which haven't been specified so this must be why its failing?)

Have you any idea what i might be doing wrong and how i can get this to bind with a user? 

UPDATE: I can get ldap to authenticate by commenting out `if (!$provider->getConnection()->isBound()) ....` in the Adldap.php file but i am not happy with this solution as this will be overwritten when i next do a composer update/install.

**Comment by sbrem00** [comment]
@jotaelesalinas are you able to assist with the above or should i try to use another method to get ldap auth working for my app? Thanks.

**Comment by jotaelesalinas** [comment]
Hi @sbrem00. Are you getting this message when trying to connect to your own server or to the testing one?

**Comment by sbrem00** [comment]
Hi @jotaelesalinas thanks for getting back to me. I'm getting this message when trying to connect to the testing LDAP server.

**Comment by jotaelesalinas** [comment]
Please, make sure that the third parameter of `Adldap::auth()->attempt()` is `true`.

If it still fails, start from scratch. I can only say that a lot of people have followed these instructions and it seems to work fine.

Use the latest version of Laravel and the libraries. If after that it does not work, use exactly the same versions that I tested it with.

**Comment by sbrem00** [comment]
I have checked the third parameter of Adldap::auth()->attempt() is true and it is.
I was using laravel 5.0.0 so i have updated to laravel 5.0.4 as you used with ldap2-laravel 3.0.5 and i still have the same issue. 

I have double checked all of the parameters in the conf files and they all look correct. 
The only one part of the guide i didn't do was  `php artisan make:auth ` as i made my own login page and login controller. I don't think this is the issue though as i have created a route to test it as shown below and am getting the same error 

```
Route::get('test-login', function(){
    dd(Adldap::auth()->attempt('uid=einstein,dc=example,dc=com', 'password', true));
});
```

If you are staying this is working for you though i must have missed something maybe a config setting? 

Would you be able to provide a stack trace of what happens when you call `Adldap::auth()->attempt()` as it would really help me debug what is happening wrong on my end?

**Comment by jotaelesalinas** [comment]
You can try saving your login page and controller, running `php artisan make:auth` and after that copying and pasting your old code in the new one, little by little, until you find the line that generates the problem. At least that's what I would do.

**Comment by sbrem00** [comment]
By putting the auth call in the route I bypass all the login stuff so it can't be anything to do with the auth controller. 
Upon further inspection of the releases i noticed that in adldap2/adldap2 v8.0.3 the admin binding is not done. The last version of adldap2/adldap2-laravel that uses this version is 2.1.3 so have downgraded to that version and all is working fine. I have no idea how you got it working with adldap2/adldap2-laravel version 3.0.5 unless you set the admin details. It doesn't seem possible to me? I have contacted the creator of Adldap2 to ask if there is a way of bypassing the auto admin binding in adldap2 v8.0.4 as i would prefer for my packages to be up to date.

**Comment by jotaelesalinas** [comment]
o_O

No idea, to be honest. But good to know!

**Comment by jotaelesalinas** [comment]
o_O

No idea, to be honest. But good to know!

**Comment by sbrem00** [comment]
@jotaelesalinas So after contacting Steve Bauman who wrote the packages he has explained that i need to get the default service provider before doing auth()->attempt() otherwise it will try and authorise as an admin. 

This can be done as by putting this in the attemptLogin() method in the login controller:

```
$provider = Adldap::getDefaultProvider();
if($provider->auth()->attempt($userdn, $password, true)) {
   //Login code
} 
```

This will stop the magic __call() method from being run and the auth() method will be run on the Provider object created. 

If you are using package version v8.04 then you should have encountered this issue too.  Not sure why you didn't but maybe you have set the default admin auth method in your env?  

I'm just letting you know just in case you would like to update your docs (or if anyone else encounters this issue).
