### ISSUE TITLE
Adldap::search()->get() doenst find any results

### ISSUE THREAD

**Issue by ngrippa** [jotaelesalinas/laravel-simple-ldap-auth#7]
`Adldap::search()->get()` fails and returns an empty array. Can somebody explain me why this happens? I can contact the LDAP server but don't get any users (an empty array instead). Even `Adldap::search()->setDn('existing dn')->get();` fails, with the dn directly copied from LDAP Browser (`uid=username,cn=xxx,ou=yyy,l=zzz,dc=de,o=mycorp`). Are there any .env variables applied to this syntax, which may can be wrong?

Note that I am able to bind to the server (if I change the admins user name or password I get an error message, so I am definitely connecting to the server!)

**Comment by jotaelesalinas** [comment]
In which file and line are you getting that error? I can’t find `Adldap::search()->get()` anywhere, only `Adldap::search()->where()->first()`.

**Comment by jotaelesalinas** [comment]
Hi @ngrippa , could you please explain what the problem was and how you solved it? Thanks.

**Comment by dinvisal** [comment]
Hi @jotaelesalinas
I got the problem with getting data for current logged in user from Active Directory.
In my case I want to get the real name from AD server.
And I can do authentication with AD server but cannot bind or search the user with ldap server the result is alway null.
here is my code in login function:
```
$provider = \Adldap::getDefaultProvider();
        if($provider->auth()->attempt($credentials['username'], $credentials['password'], true)) {            
            print("Success!");
            $user = $provider->search()->users()->find($credentials['username']);
            dump($user);
            dd();
}
```
Please help me. thanks.
